{{- if .Values.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "gocron.fullname" . }}
  labels:
    {{- include "gocron.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.persistence.mode }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  storageClassName: {{ .Values.persistence.class }}
{{- end }}
